title: Sethu Vinayagam Udhayasekar
description: PhD student under the [Prime Minister's Research Fellowship](https://pmrf.in) scheme in the [Department of Civil Engineering at Indian Institute of Technology Madras](https://civil.iitm.ac.in)
logo: /assets/img/profile_picture.jpg
show_downloads: false
theme: jekyll-theme-minimal
